### ISSUE TITLE
Remove oauth2 dependencies when using keyring

### ISSUE THREAD

**Issue by mturquette** [ototo/jic#18]
When installing jic on Mac OS X I tried to skip the oauth2 bits since I use the keyring method for storing credentials. However jic unconditionally imports oauth2 modules, causing unnecessary dependencies.

**Comment by ototo** [comment]
85e066c0031cd888202c1cad9ebed302049b11bb fixes this on a fresh Mint install for me together with 3b68553175e09586e6e45657c036db1c58ecb778 and 93a26c9486da39f6cb2cd05c97167d0a8e6c28a0.

@mturquette please confirm (I have no access to Mac OS X).

**Comment by mturquette** [comment]
Confirmed!

**Comment by ototo** [comment]
Thanks, Mike!
